### ISSUE TITLE
Badges look weird in Firefox

### ISSUE THREAD

**Issue by stof** [Async-AWS-PR/commits-since-release-counter#4]
Here is how the generated badges are displayed on my system:

![image](https://user-images.githubusercontent.com/439401/95626454-9363a100-0a7a-11eb-81f3-c9aa34f27a3e.png)

I'm using Firefox on Ubuntu 18.04.
Things are fine in Chromium.

**Comment by stof** [comment]
It seems like this can be fixed by using `font-size:11px` rather than `font-size:11` (while still working in Chromium, at least when the change is done in devtools)

**Comment by stof** [comment]
the template.svg file in the repo uses `<g font-family="..." font-size="11">`, which works fine in Firefox.
But the generated image uses `<g style="font-family: 'DejaVu Sans',Verdana,Geneva,sans-serif; font-size: 11">`, which breaks (`font-size: 11` gets detected as invalid value in CSS, and so it fallbacks to the default font-size which is 16px

**Comment by stof** [comment]
Reported at https://github.com/meyfa/php-svg/issues/96 as this conversion is done by the library.

**Comment by stof** [comment]
an alternative would be to drop the library entirely, and perform only string manipulation on the template.

**Comment by Nyholm** [comment]
Thank you for the ping. 

I've added a fix in #5. Im pragmatic and just make the easiest fix possible.

**Comment by stof** [comment]
@Nyholm the issue has now also been fixed upstream in php-svg
